spring.application.name=ideaz
spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/ideaz
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Recommended (optional)
spring.jpa.open-in-view=false

# ===============================
# = CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
